version: '2'
services:
  nginx:
    restart: always
    image: nginx:1.11
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/conf.d:/etc/nginx/conf.d"
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
